# Generated by Django 3.1.3 on 2020-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='open_for_all',
            field=models.BooleanField(default=True),
        ),
    ]
