# Generated by Django 3.1.3 on 2021-01-06 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 2, 39, 9, 54722), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
