# Generated by Django 3.1.3 on 2020-11-29 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_open_for_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 12, 48, 0, 766511), verbose_name='Date Published'),
        ),
    ]
