# Generated by Django 3.1.3 on 2021-01-05 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210105_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auth_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 0, 14, 22, 724007), verbose_name='Date Published'),
        ),
    ]
