# Generated by Django 3.1.3 on 2021-01-05 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210106_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auth_required',
            new_name='login_required',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 0, 15, 38, 477965), verbose_name='Date Published'),
        ),
    ]
